config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'users#index'
  resources :users do
    resources :photos
  end
  resources :sessions

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base

validates :email, presence: true
validates :name, presence: true

has_secure_password

has_many :photos
has_attached_file :avatar, styles: { :thumb => "100x100>" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

before_filter :authorize, only: [:new, :create, :edit, :update, :destroy]

  def index
    @photos = Photo.find_by_user_id(params[:user_id])
  end

  def new
    @user = User.find(params[:user_id])
    @photo = Photo.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user), notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])

  end

  def update

  end

  def destroy

  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fotos | Minimal, Clean, and Free Portfolio creator for Designers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Bitter:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <nav class="navbar nav-style">
      <div class="container">
        <div class="site-title text-center">
          <h1><%= link_to "Fotos", root_path %></h1>
        </div>
        <div class="main-nav">
          <ul class="nav-header nav">
            <% if current_user %>
              Hello,&nbsp <%= link_to "#{current_user.name}", user_path(current_user), class: "user-name" %>
              <li class="logout"><%= link_to "Log Out", logout_path, method: "get" %></li>

            <% else %>
              <li><%= link_to "Signup", signup_path %></li>
              <li><%= link_to "Log In", login_path %></li>
            <% end %>
          </ul>
        </div>
        <hr>
      </div>
    </nav>


  <div class="container">
    <% if flash[:alert] %>
        <div class="alert alert-info alert-dismissable" role="alert">
          <%= flash[:alert] %>
        </div>
      <% elsif flash[:notice] %>
        <div class="alert alert-success alert-dismissable" role="alert">
        <%= flash[:notice] %>
        </div>
      <% end %>
    <%= yield %>

  </div>


  <div class="footer">
    <div class="container">
      <hr>
      <p class="pull-right">&copy; 2014 Diego Avalon & Christian Danielsen</p>
      <ul class="nav nav-pills pull-left">
        <li class="disabled"><a href="#"></a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Help</a></li>
        <li><a href="#">Privacy</a></li>
        <li><a href="#">Terms</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </div>
  </div>

  </div>
</body>
</html>

app/views/photos/index.html.erb
<div class="col-md-8 col-md-offset-2 text-center user-home">
  <p class="lead">"Do not go where the path may lead, go instead where there is no path and leave a trail." </p>
  <h5>— RALPH WALDO EMERSON</h5>
  <div class="user-controls">
    <%= link_to "Edit profile", edit_user_path, class: "btn btn-default btn-lg" %>
    <!-- <button type="button" class="btn btn-default btn-lg">Edit</button> -->
    <button type="button" class="btn btn-info btn-lg">View</button>
  </div>
</div>

app/views/photos/new.html.erb
<%= render 'users/user_profile' %>

app/views/users/_user_profile.html.erb
<div class="edit-view">
  <div class="row">
    <div class="col-md-3">
      <h1>Img goes here!</h1>
      <h2>Details!</h2>
    </div>
    <div class="col-md-9">
      <ul class="nav nav-pills">
        <li><%= link_to "Add Photo", new_user_photo_path(@user) %></li>
        <li><%= link_to "Delete Photo" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'user_profile' %>

app/views/users/index.html.erb
<div class="user-home">
  <div class="col-md-8 col-md-offset-2 text-center">
    <h1 class="headline">Fotos is a <em>free</em>, easy-to-use, online portfolio generator built for Designers</h1>
    <%= link_to "Sign up now", signup_path , class: "btn btn-info btn-lg user-controls" %>
  </div>
</div>

app/views/users/new.html.erb
<div class="sign-up">
  <div class="col-xs-4 col-xs-offset-4 bg">
    <h3>Sign Up</h3>
    <%= form_for @user do |f| %>
      <!-- <div class="alert alert-danger"> -->
      <% if @user.errors.any? %>
        <div class="error_messages alert alert-danger">
          <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
          </ul>
        </div>
      <% end %>

  <div class="field form-group">
     <%= f.label :name %><br />
     <%= f.text_field :name, class: "form-control" %>
   </div>
   <div class="field form-group">
      <%= f.label :email %><br />
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="field form-group">
      <%= f.label :password %><br />
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="field form-group">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    <div class="actions"><%= f.submit "Submit", class: 'btn btn-default' %></div>
  </div>
  <% end %>
</div>